[package]
name = "rustenstein3D"
version = "0.1.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>", "Naimul Hoque <Naimul_Hoque@outlook.com>"]

[dependencies]
rsfml = { git = "https://github.com/jeremyletang/rust-sfml.git", package = "sfml" }
native = "0.1.0"